const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const ops = require('../src/editor/editorOps.js');
const tableOps = require('../src/editor/tableOps.js');
const appHelpers = require('../src/app/appHelpers.js');
const appNovelist = require('../src/app/appNovelist.js');
const appMutations = require('../src/app/appMutations.js');
const appCanvasActions = require('../src/app/appCanvasActions.js');
const panelHelpers = require('../src/panels/panelHelpers.js');
const { block, loadOutlineForTest, withIsolatedStore } = require('./helpers/common.js');
const projectPaths = require('./helpers/paths.js');

test('AI menu buttons open option menus instead of running Improve directly', () => {
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');

  assert.match(outliner, /if \(scope === 'section-menu'\)[\s\S]*setAiMenu\(\{ scope: 'section'/);
  assert.match(outliner, /onOpenAiMenu && onOpenAiMenu\(e\)/);
  assert.match(outliner, /if \(e\.key === 'ArrowDown'\)[\s\S]*setActiveIdx/);
  assert.match(outliner, /document\.addEventListener\('mousedown', onDown\)/);
  assert.match(outliner, /window\.addEventListener\('keydown', onKey, true\)/);
  assert.match(outliner, /undoActionRef\.current && undoActionRef\.current\(\)/);
  assert.match(outliner, /if \(!undoStack\.current\.length\) return false/);
  assert.match(outliner, /if \(!redoStack\.current\.length\) return false/);
  assert.match(outliner, /stopImmediatePropagation/);
  assert.match(outliner, /const \[aiPrompt, setAiPrompt\]/);
  assert.match(outliner, /title: scope === 'page' \? 'Write on this page'/);
  assert.doesNotMatch(outliner, /window\.prompt/);
  assert.match(outliner, /onClick=\{\(e\) => \{[\s\S]*pickAction\(a\.id\);/);
  assert.doesNotMatch(outliner, /onPick\('improve'\)/);
});

test('Advertised keyboard shortcuts are wired to handlers', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const appRuntime = fs.readFileSync(path.join(__dirname, '../src/app/appRuntime.js'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings/settings.jsx'), 'utf8');

  assert.match(app, /const isBackslashKey = key === '\\\\' \|\| key === '\|'/);
  assert.match(app, /e\.code === 'Backslash'/);
  assert.match(outliner, /const isBlockZoom = isMod && key === 'Enter'/);
  assert.match(outliner, /const isBlockMoveUp = e\.altKey && !isMod && key === 'ArrowUp'/);
  assert.match(outliner, /const isBlockMoveDown = e\.altKey && !isMod && key === 'ArrowDown'/);
  assert.match(outliner, /const isBlockDuplicate = isMod && lowerKey === 'd'/);
  assert.match(outliner, /const isBlockDelete = isMod && \(key === 'Backspace' \|\| key === 'Delete'\) && !isFormField/);
  assert.match(outliner, /moveBlockRef\.current && moveBlockRef\.current\(activeBlockId\(\), activeBlockId\(\), 'up'\)/);
  assert.match(outliner, /duplicateBlockRef\.current && duplicateBlockRef\.current\(activeBlockId\(\)\)/);
  assert.match(outliner, /deleteBlockRef\.current && deleteBlockRef\.current\(activeBlockId\(\)\)/);
  assert.match(outliner, /zoomBlockRef\.current && zoomBlockRef\.current\(activeBlockId\(\)\)/);
  assert.match(outliner, /if \(srcId === destId && position !== 'up' && position !== 'down'\) return/);
  assert.match(settings, /⌘ K/);
  assert.match(settings, /⌘ Z/);
  assert.match(settings, /⌥ ↑ \/ ⌥ ↓/);
});

test('Note tag picker can create new tags from the editor', () => {
  const editor = fs.readFileSync(path.join(__dirname, '../src/editor/editor.jsx'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const mutations = fs.readFileSync(path.join(__dirname, '../src/app/appMutations.js'), 'utf8');
  const sidebar = fs.readFileSync(path.join(__dirname, '../src/panels/sidebar.jsx'), 'utf8');

  assert.match(editor, /onCreateTag/);
  assert.match(editor, /placeholder="new tag"/);
  assert.match(editor, /createAndApplyTag\(\)/);
  assert.match(app, /normalizeTagName/);
  assert.match(app, /onCreateTag=\{\(raw\) =>/);
  assert.match(sidebar, /creatingTag/);
  assert.match(sidebar, /submitTag/);
  assert.match(sidebar, /onNewTag && onNewTag\(name\)/);
  assert.match(sidebar, /onDeleteTag/);
  assert.match(sidebar, /openTagMenu\(e, tag\.name\)/);
  assert.match(sidebar, /title="Remove tag"/);
  assert.match(sidebar, /Remove tag/);
  assert.match(sidebar, /if \(newTagName\.trim\(\)\) return/);
  assert.match(sidebar, /tagCreatorRef\.current\?\.contains\(e\.target\)/);
  assert.match(sidebar, /top: 50/);
  assert.match(app, /const removeTag = \(name\) =>/);
  assert.match(app, /onDeleteTag=\{removeTag\}/);
  assert.match(app, /MN_APP_MUTATIONS\.removeTagFromNotes\(notes, clean\)/);
  assert.match(mutations, /function removeTagFromNotes/);
  assert.match(mutations, /tags: \(note\.tags \|\| \[\]\)\.filter\(value => value !== tag\)/);
});

test('Note metadata edits participate in undo and redo', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const editor = fs.readFileSync(path.join(__dirname, '../src/editor/editor.jsx'), 'utf8');

  assert.match(app, /noteMetadataHistoryRef/);
  assert.match(app, /recordNoteMetadataHistory\(n, options\.historyKey\)/);
  assert.match(app, /restoreNoteMetadataSnapshot\('undo', noteId\)/);
  assert.match(app, /restoreNoteMetadataSnapshot\('redo', noteId\)/);
  assert.match(app, /if \(note\.id !== snapshot\.id\) return note/);
  assert.match(app, /title: snapshot\.title/);
  assert.match(app, /historyKey: `note:\$\{selectedNote\.id\}:title`/);
  assert.match(app, /historyKey: `note:\$\{selectedNote\.id\}:tag:\$\{t\}:remove`/);
  assert.match(editor, /className="mn-note-title-input"/);
  assert.match(editor, /onUndoNoteEdit/);
  assert.match(editor, /onRedoNoteEdit/);
  assert.match(editor, /onEndNoteMetadataEdit/);
});

test('Vaults can be created and deleted from settings with backend cleanup', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings/settings.jsx'), 'utf8');
  const store = fs.readFileSync(path.join(__dirname, '../lib/store.js'), 'utf8');
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');

  assert.match(store, /async function deleteVault\(id\)/);
  assert.match(store, /const APP_DIR_NAME = 'VispNote'/);
  assert.match(store, /const LEGACY_APP_DIR_NAMES = \['OminiNote', 'MyNote'\]/);
  assert.match(store, /const OVERRIDE_ROOT = process\.env\.VISPNOTE_HOME/);
  assert.match(store, /const ROOT = OVERRIDE_ROOT \|\| \(!fs\.existsSync\(PRIMARY_ROOT\) && LEGACY_ROOT \? LEGACY_ROOT : PRIMARY_ROOT\)/);
  assert.match(store, /async function repairConfigVaults\(cfg\)/);
  assert.match(store, /async function vaultDirectoryExists\(slug\)/);
  assert.match(store, /cfg\.vaults = validVaults/);
  assert.match(store, /Create another vault before deleting this one/);
  assert.match(store, /moveVaultToTrash\(v\.slug\)/);
  assert.match(store, /deleteVault, setActiveVault/);
  assert.match(main, /ipcMain\.handle\('mn:deleteVault'/);
  assert.match(main, /idx\.removeVault\(vaultId\)/);
  assert.match(preload, /deleteVault: \(id\) => ipcRenderer\.invoke\('mn:deleteVault', id\)/);
  assert.match(app, /const deleteVault = useCallbackA\(async \(id\) =>/);
  assert.match(app, /const refreshVaultRegistry = useCallbackA/);
  assert.match(app, /refreshVaultRegistry\(\{ reloadActive: true, reason: 'focus' \}\)/);
  assert.match(app, /onRefreshVaults=\{refreshVaultRegistry\}/);
  assert.match(app, /onCreateVault=\{createVault\}/);
  assert.match(app, /onDeleteVault=\{deleteVault\}/);
  assert.match(settings, /label="Create vault"/);
  assert.match(settings, /label="Delete current vault"/);
  assert.match(settings, /role="dialog"/);
  assert.match(settings, /aria-labelledby="mn-delete-vault-title"/);
  assert.match(settings, /Type vault name to confirm/);
  assert.match(settings, /Delete permanently/);
  assert.match(settings, /This permanently removes the current vault folder/);
});

test('Reminder center and spellcheck wiring are visible in app shell', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const appShell = fs.readFileSync(path.join(__dirname, '../src/app/appShell.jsx'), 'utf8');
  const editor = fs.readFileSync(path.join(__dirname, '../src/editor/editor.jsx'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');
  const utilityPanels = fs.readFileSync(path.join(__dirname, '../src/panels/utilityPanels.jsx'), 'utf8');

  assert.match(appShell, /function MnReminderCenter/);
  assert.match(appShell, /className="mn-reminder-center"/);
  assert.match(app, /mnCollectReminderItems\(notesWithBody\)/);
  assert.match(app, /reminderDueCount/);
  assert.match(appShell, /Reminder notifications/);
  assert.match(app, /setReminderCenterOpen\(false\)/);
  assert.match(appShell, /const visibleItems = items/);
  assert.doesNotMatch(appShell, /items\.slice\(0, 12\)/);
  assert.match(editor, /padding: '12px clamp\(18px, 4vw, 76px\) 10px clamp\(18px, 3vw, 28px\)'/);
  assert.match(editor, /borderBottom: `1px solid \$\{T\.lineSub\}`/);

  assert.match(editor, /spellCheck=\{spellCheck\}/);
  assert.match(outliner, /spellCheck=\{block\.kind === 'code' \? false : spellCheck\}/);
  assert.match(outliner, /spellCheck=\{false\}/);
  assert.match(utilityPanels, /<button onClick=\{onDismiss\}[\s\S]*>✕<\/button>/);
  assert.match(utilityPanels, /<button onClick=\{onSnooze \|\| onDismiss\}[\s\S]*>Snooze<\/button>/);
});

test('Ask AI can continue in background and reopen completed responses', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const appRuntime = fs.readFileSync(path.join(__dirname, '../src/app/appRuntime.js'), 'utf8');
  const appShell = fs.readFileSync(path.join(__dirname, '../src/app/appShell.jsx'), 'utf8');
  const ai = fs.readFileSync(path.join(__dirname, '../src/ai/ai.jsx'), 'utf8');
  const aiUi = fs.readFileSync(path.join(__dirname, '../src/ai/aiUi.jsx'), 'utf8');
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');
  const aiLib = fs.readFileSync(path.join(__dirname, '../lib/ai.js'), 'utf8');
  const ollama = fs.readFileSync(path.join(__dirname, '../lib/ollama.js'), 'utf8');
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings/settings.jsx'), 'utf8');

  assert.match(app, /const \[askAiSessions, setAskAiSessions\]/);
  assert.match(app, /const \[activeAskAiSessionId, setActiveAskAiSessionId\]/);
  assert.match(appRuntime, /function mnPickActiveAskAiSession/);
  assert.match(app, /mnPickActiveAskAiSession\(askAiSessions, activeAskAiSessionId\)/);
  assert.match(appRuntime, /allowArchivedPreferred !== false/);
  assert.match(app, /allowArchivedPreferred: false/);
  assert.match(app, /view === 'ai'/);
  assert.match(app, /<MnAiChatHistory/);
  assert.match(app, /archiveAskAiChat/);
  assert.match(app, /if \(!next\.length\) \{/);
  assert.match(app, /setAskAiSessions\(\[\]\)/);
  assert.match(app, /No AI chats/);
  assert.doesNotMatch(app, /!next\.some\(session => !session\.archived\)/);
  const deleteChatMatch = app.match(/const deleteAskAiChat = useCallbackA\([\s\S]*?\n  \}, \[activeAskAiSessionId, askAiSessions\]\);/);
  assert.ok(deleteChatMatch);
  assert.doesNotMatch(deleteChatMatch[0], /newAiSession/);
  assert.match(appShell, /function MnAiNotice/);
  assert.match(appShell, /AI response ready/);
  assert.match(app, /onOpen=\{openAskAi\}/);
  assert.match(app, /session=\{activeAskAiSession\}/);
  assert.match(app, /setSession=\{setActiveAskAiSession\}/);
  assert.match(app, /onBackgroundComplete=\{notifyAskAiComplete\}/);
  assert.match(app, /onCreateNote=\{\(\{ title, body, tags: noteTags \}\) => createNote\(\{ title, body, tags: noteTags \|\| \[\] \}, \{ open: false \}\)\}/);
  assert.match(app, /onTagCurrentNote=\{tagCurrentNoteFromAi\}/);
  assert.match(app, /id: 'search-notes'/);
  assert.match(app, /id: 'append-to-note'/);
  assert.match(app, /id: 'add-todo-to-note'/);
  assert.match(app, /id: 'add-reminder-to-note'/);
  assert.match(app, /id: 'link-note'/);
  assert.match(app, /window\.mn\?\.searchDetailedStatus/);

  assert.match(ai, /const aiSession = session \|\| localSession/);
  assert.match(ai, /window\.MN_AI_ACTIONS\?\.classifyPrompt/);
  assert.match(ai, /function mnBuildAskThreadMessages\(priorMessages = \[\], currentQuery = '', options = \{\}\)/);
  assert.match(ai, /function mnBuildAskThreadPrompt\(priorMessages = \[\], currentQuery = ''\)/);
  assert.match(ai, /function mnRecentAskThreadNote\(priorMessages = \[\]\)/);
  assert.match(ai, /function mnBuildContextualActionQuery\(priorMessages = \[\], currentQuery = ''\)/);
  assert.match(ai, /const MN_AI_VIRTUAL_TOOLS = \[/);
  assert.match(ai, /name: 'answer-notes'/);
  assert.match(ai, /name: 'edit-current-page'/);
  assert.match(ai, /function mnAiCurrentContextMessage\(currentNote\)/);
  assert.match(ai, /const runLlmOrchestrator = async/);
  assert.match(ai, /await runLlmOrchestrator\(\{ q, actionQuery, priorMessages, jobId, run \}\)/);
  assert.match(ai, /const scrollVersion = messages\.map/);
  assert.match(ai, /onScroll=\{rememberScrollPosition\}/);
  assert.match(ai, /data-mn-chat-bottom="true"/);
  assert.match(ai, /const runActionPlan = async/);
  assert.match(ai, /traceLabels/);
  assert.match(ai, /aiRuntime\.traceLabel/);
  assert.match(ai, /tool\.run/);
  assert.match(ai, /tool\.done/);
  assert.match(ai, /const isPureInspectionRequest = \(text\) =>/);
  assert.match(ai, /if \(onlyInspectionSteps && isPureInspectionRequest\(q\)\) return plan/);
  assert.match(ai, /planAppActionsWithModel\(actionQuery, route\.plan, jobId, run, priorMessages\)/);
  assert.match(ai, /const actionQuery = mnBuildContextualActionQuery\(priorMessages, q\)/);
  assert.match(ai, /query: actionQuery, aiActions: window\.MN_AI_ACTIONS, appRegistry: window\.MN_APP_ACTIONS/);
  assert.match(ai, /const toolMessages = mnBuildAskThreadMessages\(priorMessages, q, \{ limit: 8 \}\)/);
  assert.match(ai, /const qForAsk = mnBuildAskThreadPrompt\(priorMessages, q\)/);
  assert.match(ai, /const chatMessages = mnBuildAskThreadMessages\(priorMessages, q, \{ limit: 8 \}\)/);
  assert.match(ai, /window\.mn\.ai\.ask\(vaultId, prompt/);
  assert.match(ai, /bodyFrom === 'previous-answer'/);
  assert.match(ai, /tag-created-note/);
  assert.match(ai, /if \(stoppedJobRef\.current === jobId\) return/);
  assert.match(aiUi, /function MnAiChatHistory/);
  assert.match(aiUi, /provider !== 'ollama'/);
  assert.match(aiUi, /AI chats/);
  assert.match(aiUi, /Show archived chats/);
  assert.match(aiUi, /Archived <span/);
  assert.match(aiUi, /Archive chat/);
  assert.match(aiUi, /Restore chat/);
  assert.match(aiUi, /function mnAiRowActionButton/);
  assert.match(ai, /embedded = false/);
  assert.match(ai, /const MN_ASK_SUGGESTIONS = \[/);
  assert.match(ai, /function mnAskStatusText/);
  assert.match(ai, /function mnAiProviderLabel/);
  assert.match(ai, /function mnAskFooterHint/);
  assert.match(ai, /provider !== 'ollama'/);
  assert.match(ai, /openrouter: 'OpenRouter'/);
  assert.match(ai, /\$\{providerLabel\} ready/);
  assert.match(ai, /Enter to ask · Shift\+Enter for newline/);
  assert.match(ai, /const \[openSources, setOpenSources\]/);
  assert.match(ai, /const onComposerKeyDown = \(e\) =>/);
  assert.match(ai, /rows=\{1\}/);
  assert.match(ai, /aria-expanded=\{sourcesOpen\}/);
  assert.match(ai, /Sources \(\{m\.sources\.length\}\)/);
  assert.match(ai, /function mnParseAiResponseBlocks\(text\)/);
  assert.match(ai, /function mnAiLooksLikeSectionLabel\(text\)/);
  assert.match(ai, /promoted: true/);
  assert.match(ai, /function MnAiFormattedResponse\(\{ text, T \}\)/);
  assert.match(ai, /gridTemplateColumns: block\.type === 'ol'/);
  assert.match(ai, /<MnAiFormattedResponse text=\{m\.text\} T=\{T\} \/>/);
  assert.match(ai, /mnAskPrimaryButton/);
  assert.match(ai, /mnAskSecondaryButton/);
  assert.match(ai, /Clear/);
  assert.match(aiUi, /onContextMenu=\{\(e\) => openContextMenu\(e, session\)\}/);
  assert.match(aiUi, /function MnAiContextMenuItem/);
  assert.match(aiUi, /Delete chat/);
  assert.match(aiUi, /Use the row buttons or right-click for chat actions/);
  assert.match(aiUi, /onRename\(renameId, renameValue\.trim\(\) \|\| 'New chat'\)/);
  assert.match(ai, /MN_AI_REPORT/);
  assert.match(ai, /Report AI output/);
  assert.match(ai, /mnAiProviderReportInfo/);
  assert.match(ai, /navigator\.clipboard\?\.writeText\(report\)/);
  assert.match(ai, /window\.mn\.openExternal\(info\.url\)/);
  assert.match(ai, /Semantic search ready/);
  assert.match(ai, /Ask about the vault or ask for a page action/);
  assert.match(ai, /backgroundRef\.current = true/);
  assert.match(ai, /Run in background/);
  assert.match(ai, /Stop/);
  assert.match(ai, /const stopRun = async/);
  assert.match(ai, /window\.mn\?\.ai\?\.cancel\?\.\(jobId\)/);
  assert.match(ai, /Stopped\./);
  assert.match(ai, /onBackgroundComplete && onBackgroundComplete/);
  assert.match(ai, /completedAt: new Date\(\)\.toISOString\(\)/);

  assert.match(preload, /cancel:\s+\(jobId\) => ipcRenderer\.invoke\('mn:ai\.cancel', jobId\)/);
  assert.match(preload, /openExternal: \(url\) => ipcRenderer\.invoke\('mn:openExternal', url\)/);
  assert.match(main, /ipcMain\.handle\('mn:ai\.cancel'/);
  assert.match(main, /ipcMain\.handle\('mn:openExternal'/);
  assert.match(aiLib, /const STATUS_CACHE_MS/);
  assert.match(aiLib, /const OLLAMA_KEEP_ALIVE = '10m'/);
  assert.match(aiLib, /const PROVIDERS = \{/);
  assert.match(aiLib, /Decide whether to answer directly, inspect note context, ask a clarifying question, or call tools/);
  assert.match(aiLib, /Format intentionally: use markdown headings for section titles, bullets only for real list items/);
  assert.match(aiLib, /Emoji are allowed when they naturally improve tone or scanability/);
  assert.match(aiLib, /openrouterApiKey/);
  assert.match(aiLib, /openaiApiKey/);
  assert.match(aiLib, /anthropicApiKey/);
  assert.match(aiLib, /geminiApiKey/);
  assert.match(aiLib, /async function providerChat/);
  assert.match(aiLib, /https:\/\/openrouter\.ai\/api\/v1/);
  assert.match(aiLib, /https:\/\/api\.openai\.com\/v1/);
  assert.match(aiLib, /https:\/\/api\.anthropic\.com/);
  assert.match(aiLib, /https:\/\/generativelanguage\.googleapis\.com\/v1beta/);
  assert.match(aiLib, /anthropic-version/);
  assert.match(aiLib, /generateContent/);
  assert.match(aiLib, /const cancellableJobs = new Map\(\)/);
  assert.match(aiLib, /function cancelJob\(jobId\)/);
  assert.match(aiLib, /controller\.abort\(\)/);
  assert.match(aiLib, /cancelJob,/);
  assert.match(aiLib, /statusCache/);
  assert.match(aiLib, /ollama\.chat\(options\.model \|\| CONFIG\.chatModel, providerMessages, \{/);
  assert.match(aiLib, /timeoutMs: options\.timeoutMs/);
  assert.match(aiLib, /function isEmbeddingUnsupportedError/);
  assert.match(aiLib, /function markEmbedModelFailure/);
  assert.match(aiLib, /EMBED_MODEL_UNSUPPORTED/);
  assert.match(aiLib, /embedModelReason/);
  assert.match(aiLib, /String\(systemMessage \|\| ''\)\.trim\(\) \|\| EDIT_SYSTEM_PROMPT/);
  assert.match(main, /async function prepareAiEditPayload/);
  assert.doesNotMatch(main, /payload\.systemMessage \? capString\(payload\.systemMessage/);
  assert.doesNotMatch(main, /payload\.model \? capString\(payload\.model/);
  assert.match(ollama, /async function embed\(model, text, opts = \{\}\)/);
  assert.match(ollama, /signal: opts\.signal/);
  assert.match(ollama, /keep_alive: opts\.keep_alive/);

  assert.match(settings, /const MN_AI_PROVIDERS = \[/);
  assert.match(settings, /id: 'openrouter'/);
  assert.match(settings, /id: 'openai'/);
  assert.match(settings, /id: 'anthropic'/);
  assert.match(settings, /id: 'gemini'/);
  assert.match(settings, /id: 'custom'/);
  assert.match(settings, /PII reduction/);
  assert.match(settings, /Provider API base URL/);
  assert.match(settings, /Cloud providers are used for chat, note creation, and editing/);
});

test('Canvas workspace is wired through storage, navigation, and note embeds', () => {
  const html = fs.readFileSync(path.join(__dirname, '../vispnote.html'), 'utf8');
  const rendererEntry = fs.readFileSync(projectPaths.src.main, 'utf8');
  const store = fs.readFileSync(path.join(__dirname, '../lib/store.js'), 'utf8');
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const appRuntime = fs.readFileSync(path.join(__dirname, '../src/app/appRuntime.js'), 'utf8');
  const canvasActions = fs.readFileSync(path.join(__dirname, '../src/app/appCanvasActions.js'), 'utf8');
  const canvasModel = fs.readFileSync(path.join(__dirname, '../src/canvas/canvasModel.js'), 'utf8');
  const sidebar = fs.readFileSync(path.join(__dirname, '../src/panels/sidebar.jsx'), 'utf8');
  const editor = fs.readFileSync(path.join(__dirname, '../src/editor/editor.jsx'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');
  const canvas = fs.readFileSync(path.join(__dirname, '../src/canvas/canvas.jsx'), 'utf8');

  assert.match(html, /src="build\/renderer\/app\.js"/);
  assert.match(rendererEntry, /import '\.\/canvas\/canvas\.jsx';/);
  assert.match(store, /function canvasDir\(slug\)/);
  assert.match(store, /async function listCanvases\(vaultId\)/);
  assert.match(store, /async function saveCanvas\(vaultId, canvas\)/);
  assert.match(store, /async function deleteCanvas\(vaultId, canvasId\)/);
  assert.match(main, /ipcMain\.handle\('mn:listCanvases'/);
  assert.match(main, /ipcMain\.handle\('mn:getCanvas'/);
  assert.match(preload, /listCanvases: \(vaultId\) => ipcRenderer\.invoke\('mn:listCanvases', vaultId\)/);
  assert.match(preload, /saveCanvas: \(vaultId, canvas\) => ipcRenderer\.invoke\('mn:saveCanvas', vaultId, canvas\)/);
  assert.match(sidebar, /label="Canvas"/);
  assert.match(sidebar, /canvasActive/);
  assert.match(app, /const \[canvases, setCanvases\]/);
  assert.match(app, /const \[activeCanvas, setActiveCanvas\]/);
  assert.match(app, /window\.mn\.listCanvases\(vaultId\)/);
  assert.match(appRuntime, /const MN_APP_CANVAS_ACTIONS = window\.MN_APP_CANVAS_ACTIONS/);
  assert.match(app, /MN_APP_CANVAS_ACTIONS\.openCanvas\(canvasId, canvasActionContext\(\)\)/);
  assert.match(app, /MN_APP_CANVAS_ACTIONS\.createCanvas\(title, options, canvasActionContext\(\)\)/);
  assert.match(canvasActions, /async function openCanvas\(canvasId, ctx = \{\}\)/);
  assert.match(canvasActions, /ctx\.mn\.getCanvas\(ctx\.activeVaultId, canvasId\)/);
  assert.match(canvasActions, /async function createCanvas/);
  assert.match(canvasActions, /async function saveCanvas/);
  assert.match(canvasActions, /async function deleteCanvas/);
  assert.match(app, /view === 'canvas'/);
  assert.match(app, /<MnCanvasPanel/);
  assert.match(editor, /allCanvases=\{canvases\}/);
  assert.match(outliner, /id: 'canvas'/);
  assert.match(outliner, /\{\{canvas/);
  assert.match(outliner, /<MnCanvasPicker/);
  assert.match(outliner, /<MnCanvasEmbed/);
  assert.match(canvasModel, /const MN_CANVAS_TOOLS = \[/);
  assert.match(canvasModel, /window\.MN_CANVAS_MODEL/);
  assert.match(canvas, /function MnCanvasPanel/);
  assert.match(canvas, /function MnCanvasCardMenu/);
  assert.match(canvas, /onContextMenu=\{\(e\) => openCanvasCardMenu\(e, canvas\)\}/);
  assert.match(canvas, /Delete canvas/);
  assert.match(canvas, /function MnCanvasEditor/);
  assert.match(canvas, /function MnCanvasEmbed/);
});

test('Novelist mode is a vault type with settings, templates, workflow, and dashboard wiring', () => {
  const store = fs.readFileSync(path.join(__dirname, '../lib/store.js'), 'utf8');
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const appRuntime = fs.readFileSync(path.join(__dirname, '../src/app/appRuntime.js'), 'utf8');
  const helpers = fs.readFileSync(path.join(__dirname, '../src/app/appHelpers.js'), 'utf8');
  const appNovelistSource = fs.readFileSync(path.join(__dirname, '../src/app/appNovelist.js'), 'utf8');
  const panelHelpersSource = fs.readFileSync(path.join(__dirname, '../src/panels/panelHelpers.js'), 'utf8');
  const sidebar = fs.readFileSync(path.join(__dirname, '../src/panels/sidebar.jsx'), 'utf8');
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings/settings.jsx'), 'utf8');
  const panels = fs.readFileSync(path.join(__dirname, '../src/panels/panels.jsx'), 'utf8');
  const editor = fs.readFileSync(path.join(__dirname, '../src/editor/editor.jsx'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');
  const graph = fs.readFileSync(path.join(__dirname, '../src/panels/graph.jsx'), 'utf8');
  const notelist = fs.readFileSync(path.join(__dirname, '../src/panels/notelist.jsx'), 'utf8');
  const ai = fs.readFileSync(path.join(__dirname, '../src/ai/ai.jsx'), 'utf8');

  assert.match(store, /novelistMode: !!meta\.novelistMode/);
  assert.match(store, /workflowStates: Array\.isArray\(meta\.workflowStates\) \? normalizeWorkflowStates\(meta\.workflowStates\) : null/);
  assert.match(store, /async function createVault\(name, options = \{\}\)/);
  assert.match(store, /fs\.existsSync\(vaultDir\(finalSlug\)\)/);
  assert.match(main, /store\.createVault\(name, options\)/);
  assert.match(preload, /createVault: \(name, options\) => ipcRenderer\.invoke\('mn:createVault', name, options\)/);
  assert.match(appNovelistSource, /const MN_NOVELIST_TAGS = \[/);
  assert.match(appNovelistSource, /novel-act/);
  assert.match(appNovelistSource, /\[\[Act 1\]\]/);
  assert.match(appNovelistSource, /\[\[Chapter 1\]\]/);
  assert.match(appNovelistSource, /\[\[Scene 1\]\]/);
  assert.match(appNovelistSource, /const MN_NOVELIST_WORKFLOW_STATES = \[/);
  assert.match(app, /sourceWorkflowStates = null/);
  assert.match(app, /includeStarterNotes: false/);
  assert.match(app, /workflowStates: nextWorkflowStates/);
  assert.match(app, /mnBuildNovelistStarterNotes\(normalizedSourceNotes, mnMdToBlocks, vaultId\)/);
  assert.match(appNovelistSource, /function mnDirtyNoteKey\(vaultId, noteId\)/);
  assert.match(app, /const vaultActivationSeq = useRefA\(0\)/);
  assert.match(app, /const activationSeq = \+\+vaultActivationSeq\.current/);
  assert.match(app, /if \(activationSeq !== vaultActivationSeq\.current\) return/);
  assert.match(app, /const dirtyRevisionRef = useRefA\(0\)/);
  assert.match(app, /revision: \+\+dirtyRevisionRef\.current/);
  assert.match(app, /current\.revision !== revision/);
  assert.match(app, /window\.mn\.onFlushDirtyNotes/);
  assert.match(app, /entry\.vaultId === activeVaultId/);
  assert.match(app, /notes: targetNotes, tags: targetTags/);
  assert.match(app, /saveVaultMeta\(activeVaultId, \{ novelistMode: false, workflowStates: null \}\)/);
  assert.match(app, /novelistMode: false, workflowStates: null/);
  assert.match(app, /workflowStates: vaultType === 'novelist' \? MN_NOVELIST_WORKFLOW_STATES : null/);
  assert.match(app, /const normalWorkflowStates = useMemoA/);
  assert.match(app, /const novelistWorkflowStates = useMemoA/);
  assert.match(app, /activeVault\?\.novelistMode \? novelistWorkflowStates : normalWorkflowStates/);
  assert.match(app, /saveVaultMeta\(activeVaultId, \{ workflowStates: next \}\)/);
  assert.doesNotMatch(app, /setTweak\('workflowStates', MN_NOVELIST_WORKFLOW_STATES\)/);
  assert.match(appNovelistSource, /function mnBuildNovelistStarterNotes/);
  assert.match(appNovelistSource, /function mnBuildNovelistStructure/);
  assert.match(appNovelistSource, /function mnNovelOutlineLinks/);
  assert.match(appNovelistSource, /function mnBodyPropertyValue/);
  assert.match(appNovelistSource, /function mnSetBodyProperty/);
  assert.match(appNovelistSource, /function mnRemoveBodyProperty/);
  assert.match(appNovelistSource, /function mnNoteOrderValue/);
  assert.match(appRuntime, /function collectWorkflowNotes/);
  assert.match(helpers, /split\('\|'\)\[0\]/);
  assert.match(helpers, /function bodyPropertyTitle/);
  assert.match(helpers, /addStage\('chapter', chapter\)/);
  assert.match(helpers, /addStage\('scene', scene\)/);
  assert.match(app, /mnNormalizeNovelistLegacyTags/);
  assert.match(app, /mnNormalizeNovelistLegacyBody/);
  assert.match(app, /mnEnsureScenePlotPoints/);
  assert.match(app, /selectedStage === 'act'/);
  assert.match(app, /selectedStage === 'chapter'/);
  assert.match(app, /stageByNoteId/);
  assert.match(app, /mnNovelEnsureWikiLink/);
  assert.match(app, /mnNovelEnsureWikiLinkInSection/);
  assert.match(app, /mnNovelUpsertPropertyLink/);
  assert.match(app, /const updateWorkflowNoteStatus = useCallbackA/);
  assert.match(app, /mnSetBodyProperty\(body, 'status', workflow\)/);
  assert.match(app, /const setNovelistOrder = useCallbackA/);
  assert.match(app, /const renameNoteTitle = useCallbackA/);
  assert.match(app, /const convertNovelistType = useCallbackA/);
  assert.match(app, /const graphVisibleNotes = useMemoA/);
  assert.match(app, /const setActiveVaultNovelistMode = useCallbackA/);
  assert.match(app, /view === 'novelist'/);
  assert.match(app, /<MnNovelistPanel/);
  assert.match(app, /vaultId=\{activeVaultId\}/);
  assert.match(app, /createNote\(\{ title, body, tags: noteTags \|\| \[\] \}, \{ open: false \}\)/);
  assert.match(app, /onLinkChapter=\{linkNovelistChapter\}/);
  assert.match(app, /onLinkScene=\{linkNovelistScene\}/);
  assert.match(app, /onSetOrder=\{setNovelistOrder\}/);
  assert.match(app, /onRenameNote=\{renameNoteTitle\}/);
  assert.match(app, /onConvertNoteType=\{convertNovelistType\}/);
  assert.match(app, /onDeleteNote=\{requestDeleteNote\}/);
  assert.match(app, /const removeNovelistSupportingType = \(name\) =>/);
  assert.match(app, /setTags\(ts => ts\.filter\(t => t\.name !== clean\)\)/);
  assert.match(app, /onCreateTag=\{addTag\}/);
  assert.match(app, /onRemoveSupportingType=\{removeNovelistSupportingType\}/);
  assert.match(app, /novelistPath=\{activeVault\?\.novelistMode/);
  assert.match(app, /novelistStructure=\{activeVault\?\.novelistMode/);
  assert.match(app, /onSetVaultNovelistMode=\{setActiveVaultNovelistMode\}/);
  assert.match(sidebar, /label="Novelist"/);
  assert.match(sidebar, /Novelist vault/);
  assert.match(settings, /Vault mode/);
  assert.match(settings, /Novelist vault/);
  assert.match(panels, /function MnNovelistPanel/);
  assert.match(panels, /activeTab/);
  assert.match(panels, /Plan/);
  assert.match(panels, /Status/);
  assert.match(panels, /AI Config/);
  assert.doesNotMatch(panels, /CreateButtonGroup/);
  assert.match(panels, /Story Structure/);
  assert.match(panels, /Act -> Chapter -> Scene/);
  assert.match(panels, /function MnNovelistPanel[\s\S]*childrenByActId/);
  assert.match(panels, /Word Count by Act/);
  assert.match(panels, /Character Appearance Heat Map/);
  assert.match(panelHelpersSource, /mn_novelist_ai_config_v2/);
  assert.match(panels, /supportingTypes = \(tags \|\| \[\]\)/);
  assert.match(panels, /normalizeSupportingTypeTag/);
  assert.match(panels, /onCreateTag\?\.\(tagName\)/);
  assert.match(panels, /onRemoveSupportingType\?\.\(type\.tag\)/);
  assert.match(panels, /Add type/);
  assert.match(panels, /Remove type/);
  assert.match(panels, /\+ Note/);
  assert.match(panels, /novel-character/);
  assert.match(panels, /novel-research/);
  assert.match(panels, /novel-revision/);
  assert.match(panels, /No chapters linked/);
  assert.match(panels, /No scenes linked/);
  assert.match(panels, /\+ \{type === 'chapter' \? 'Chapter' : 'Scene'\}/);
  assert.match(panels, /Link existing chapter/);
  assert.match(panels, /Link existing scene/);
  assert.match(panels, /Attach to act/);
  assert.match(panels, /Create parent act/);
  assert.match(panels, /Convert to scene/);
  assert.match(panels, /Attach to chapter/);
  assert.match(panels, /Create parent chapter/);
  assert.match(panels, /Set order/);
  assert.match(panels, /const \[editDialog, setEditDialog\] = useStateP\(null\)/);
  assert.match(panels, /Order must be a number or blank/);
  assert.doesNotMatch(panels, /window\.prompt\('Rename note:'/);
  assert.doesNotMatch(panels, /window\.prompt\('Set order:: value:'/);
  assert.match(panels, /showLinkNotice/);
  assert.match(panels, /LinkNoticeChip/);
  assert.match(panels, /linkNotice\.text/);
  assert.match(panels, /linkNotice\.parentId/);
  assert.match(panels, /Linked to \$\{linkedTo\.title/);
  assert.match(panels, /Unlinked chapters/);
  assert.match(panels, /Unlinked scenes/);
  assert.match(panels, /linkNoticeTimer/);
  assert.match(panels, /onContextMenu=\{\(e\) => openNoteMenu\(e, note\)\}/);
  assert.match(panels, /closeOnEscape/);
  assert.match(panels, /Delete note/);
  assert.match(panels, /Choose act for new Chapter/);
  assert.match(panels, /Create standalone/);
  assert.match(panels, /createChapterForAct/);
  assert.match(panels, /createSceneForChapter/);
  assert.match(editor, /novelistPath = null/);
  assert.match(editor, /workflowStatus = ''/);
  assert.match(editor, /onSetWorkflowStatus/);
  assert.match(editor, /onCreateLinkedNote/);
  assert.match(editor, /noteTags=\{note\.tags \|\| \[\]\}/);
  assert.match(editor, /vaultId=\{vaultId\}/);
  assert.match(outliner, /noteTags = \[\]/);
  assert.match(outliner, /vaultId = ''/);
  assert.match(outliner, /window\.mnReadNovelistAiConfig\?\.\(vaultId\)/);
  assert.match(outliner, /defaultPromptId: config\.defaultPromptId/);
  assert.match(outliner, /Target length: up to \$\{novelConfig\.wordLimit\} words/);
  assert.match(outliner, /Novelist writing prompt \(\$\{activePrompt\.name \|\| 'Default'\}\):/);
  assert.match(graph, /All novelist notes/);
  assert.match(graph, /Act structure/);
  assert.match(graph, /Characters \+ scenes/);
  assert.match(graph, /Plot threads \+ scenes/);
  assert.match(graph, /Research \+ scenes/);
  assert.match(graph, /padding: '0 88px 0 24px'/);
  assert.match(graph, /right: 64/);
  assert.match(notelist, /function MnNoteList[\s\S]*novelistStructure = null/);
  assert.match(notelist, /allNotes = null/);
  assert.match(notelist, /const sourceNotes = allNotes \|\| notes \|\| \[\]/);
  assert.match(notelist, /const GroupHeader/);
  assert.match(notelist, /const CollectionHeader/);
  assert.match(notelist, /chaptersForAct/);
  assert.match(notelist, /scenesForChapter/);
  assert.match(notelist, /const chapterIds = new Set/);
  assert.match(notelist, /linkedTo=\{`Linked to \$\{act\.title/);
  assert.match(notelist, /parentByChapterId/);
  assert.match(notelist, /parentBySceneId/);
  assert.match(notelist, /Unlinked chapters/);
  assert.match(notelist, /looseScenes/);
  assert.match(panels, /Supporting Notes/);
  assert.match(panels, /Workflow Status Counts/);
  assert.match(panels, /AI Config/);
  assert.match(panels, /Words/);
  assert.match(panels, /Default writing prompt/);
  assert.match(panelHelpersSource, /AI write novel/);
  assert.match(panels, /defaultPromptId/);
  assert.match(panelHelpersSource, /mn_novelist_ai_config_v2/);
  assert.match(panelHelpersSource, /function mnNovelistAiConfigKey\(vaultId = ''\)/);
  assert.match(panelHelpersSource, /function mnReadNovelistAiConfig\(vaultId = ''\)/);
  assert.match(panelHelpersSource, /root\.mnReadNovelistAiConfig = api\.mnReadNovelistAiConfig/);
  assert.match(panels, /addAiPrompt/);
  assert.match(panels, /updateAiPrompt/);
  assert.doesNotMatch(panels, /AI Actions/);
  assert.doesNotMatch(panels, /const aiActions = \[/);
  assert.doesNotMatch(panels, /Novel Plot Board/);
  assert.match(ai, /initialQuery/);
});

test('Review fixes wire settings, rollup, reminders, and safe note paths', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const mutations = fs.readFileSync(path.join(__dirname, '../src/app/appMutations.js'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');
  const todosPanel = fs.readFileSync(path.join(__dirname, '../src/panels/todosPanel.jsx'), 'utf8');
  const utilityPanels = fs.readFileSync(path.join(__dirname, '../src/panels/utilityPanels.jsx'), 'utf8');
  const sidebar = fs.readFileSync(path.join(__dirname, '../src/panels/sidebar.jsx'), 'utf8');
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings/settings.jsx'), 'utf8');
  const markdown = fs.readFileSync(path.join(__dirname, '../src/shared/markdown.jsx'), 'utf8');
  const store = fs.readFileSync(path.join(__dirname, '../lib/store.js'), 'utf8');

  assert.match(app, /tweaks\.sortBy/);
  assert.match(app, /tweaks\.pinnedFirst/);
  assert.match(app, /parseDefaultTags: mnParseDefaultTags/);
  assert.match(app, /defaultTags: tweaks\.defaultTags/);
  assert.match(mutations, /function cleanNoteTags/);
  assert.match(app, /toggleCheckFromAggregate = \(it\) =>/);
  assert.match(app, /it\.blockId/);
  assert.match(app, /mnCollectReminderItems\(notesWithBody\)/);
  assert.match(app, /mnWriteSnoozedReminder/);

  assert.match(outliner, /spellCheck=\{block\.kind === 'code' \? false : spellCheck\}/);
  assert.match(outliner, /indentGuides && Array\.from/);
  assert.match(outliner, /autoLink \? before\.match/);
  assert.match(outliner, /collapseByDefault && cmd\.kind === 'heading'/);
  assert.match(outliner, /window\.MN_REMIND\?\.defaultText/);
  assert.doesNotMatch(outliner, /@remind\(tomorrow 9am\)/);

  assert.match(markdown, /window\.MN_REMIND/);
  assert.match(markdown, /function mnDefaultReminderText/);
  assert.match(todosPanel, /blockId: block\.id/);
  assert.match(todosPanel, /isReminderOnly/);
  assert.match(utilityPanels, /onSnooze \|\| onDismiss/);
  assert.match(utilityPanels, /rollupFormat === 'short'/);
  assert.match(sidebar, /label="Daily rollup"/);
  assert.match(sidebar, /const rollupCount = notes\.length/);

  assert.match(settings, /<StaticValue T=\{T\}>Markdown<\/StaticValue>/);
  assert.match(settings, /<StaticValue T=\{T\}>Local only<\/StaticValue>/);
  assert.match(settings, /<StaticValue T=\{T\}>Always on<\/StaticValue>/);
  assert.match(store, /function validateNoteId/);
  assert.match(store, /\^\[A-Za-z0-9_-\]\+\$/);
  assert.match(store, /path\.relative\(dir, file\)/);
});

test('Electron installs native edit context menu for right-click copy paste cut', () => {
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const html = fs.readFileSync(path.join(__dirname, '../vispnote.html'), 'utf8');
  const builder = fs.readFileSync(path.join(__dirname, '../electron-builder.yml'), 'utf8');
  const linuxAfterInstall = fs.readFileSync(path.join(__dirname, '../scripts/linux-after-install.sh'), 'utf8');
  const icon = fs.statSync(path.join(__dirname, '../assets/vispnote-icon.png'));
  const linuxIconSizes = [16, 24, 32, 48, 64, 128, 256, 512, 1024];

  assert.match(main, /APP_ICON_PATH = path\.join\(__dirname, 'assets', 'vispnote-icon\.png'\)/);
  assert.match(main, /const APP_NAME = 'VispNote'/);
  assert.match(main, /app\.setName\(APP_NAME\)/);
  assert.match(main, /app\.setDesktopName\('vispnote\.desktop'\)/);
  assert.match(main, /label: visible \? `Hide \$\{APP_NAME\}` : `Show \$\{APP_NAME\}`/);
  assert.match(main, /label: `Quit \$\{APP_NAME\}`/);
  assert.match(main, /tray\.setToolTip\(APP_NAME\)/);
  assert.match(main, /title: APP_NAME/);
  assert.match(main, /const fs = require\('fs'\)/);
  assert.match(main, /function createAppIcon\(\)/);
  assert.match(main, /function createFallbackIcon\(\)/);
  assert.match(main, /if \(!image\.isEmpty\(\)\) return image/);
  assert.match(main, /nativeImage\.createFromPath\(APP_ICON_PATH\)/);
  assert.match(main, /nativeImage\.createFromDataURL/);
  assert.match(main, /new Tray\(createAppIcon\(\)\)/);
  assert.match(main, /icon: createAppIcon\(\)/);
  assert.match(main, /app\.dock\?\.setIcon\(createAppIcon\(\)\)/);
  assert.match(main, /function attachEditContextMenu\(win\)/);
  assert.match(main, /webContents\.on\('context-menu'/);
  assert.match(main, /params\.isEditable/);
  assert.match(main, /dictionarySuggestions/);
  assert.match(main, /replaceMisspelling\(word\)/);
  assert.match(main, /addWordToSpellCheckerDictionary\(params\.misspelledWord\)/);
  assert.match(main, /spellcheck: true/);
  assert.match(main, /setSpellCheckerEnabled\(true\)/);
  assert.match(main, /availableSpellCheckerLanguages/);
  assert.match(main, /setSpellCheckerLanguages\(\[spellLanguage \|\| 'en-US'\]\)/);
  assert.match(main, /ipcMain\.handle\('mn:spellcheck'/);
  assert.match(main, /role: 'cut'/);
  assert.match(main, /role: 'copy'/);
  assert.match(main, /role: 'paste'/);
  assert.match(main, /role: 'selectAll'/);
  assert.match(main, /attachEditContextMenu\(win\)/);
  assert.ok(icon.size > 0);
  assert.match(html, /type="image\/png" href="assets\/vispnote-icon\.png"/);
  assert.match(builder, /appId: com\.vispnote\.app/);
  assert.match(builder, /productName: VispNote/);
  assert.match(builder, /- assets\/\*\*\/*/);
  assert.match(builder, /!VispNote\/\*\*\/*/);
  assert.match(builder, /!OminiNote\/\*\*\/*/);
  assert.match(builder, /!MyNote\/\*\*\/*/);
  assert.match(builder, /!vispnote-web\/\*\*\/*/);
  assert.match(builder, /icon: assets\/linux-icons/);
  assert.match(builder, /afterInstall: scripts\/linux-after-install\.sh/);
  assert.match(builder, /shortcutName: VispNote/);
  for (const size of linuxIconSizes) {
    assert.ok(fs.statSync(path.join(__dirname, `../assets/linux-icons/${size}x${size}.png`)).size > 0);
  }
  assert.match(linuxAfterInstall, /gtk-update-icon-cache -q -t -f \/usr\/share\/icons\/hicolor/);
  assert.match(linuxAfterInstall, /xdg-icon-resource forceupdate --theme hicolor/);
});

test('URL plugins follow the external URL security policy and surface failures', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const plugins = fs.readFileSync(path.join(__dirname, '../src/shared/plugins.js'), 'utf8');

  assert.match(app, /appActionRegistry\.run\(action\.id, \{\}, \{ confirmed: action\.risk === 'external' \}\)/);
  assert.match(app, /risk: plugin\.type === 'open-url' \? 'external' : 'safe'/);
  assert.match(plugins, /Launch a trusted HTTPS page or mail link/);
  assert.match(app, /const runPlugin = useCallbackA\(async \(plugin\) =>/);
  assert.ok(app.includes("if (!/^(https:\\/\\/|mailto:)/i.test(url)) {"));
  assert.match(app, /must start with https:\/\/ or mailto:/);
  assert.match(app, /const res = await window\.mn\.openExternal\(url\)/);
  assert.match(app, /if \(res && res\.ok === false\) throw new Error/);
  assert.match(app, /showAppNotice\('Could not open link'/);
  assert.doesNotMatch(app, /must start with http:\/\/ or https:\/\//);
});

test('Zotero reader is wired as a read-only AI app action', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const plugins = fs.readFileSync(path.join(__dirname, '../src/shared/plugins.js'), 'utf8');
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings/settings.jsx'), 'utf8');
  const ai = fs.readFileSync(path.join(__dirname, '../src/ai/ai.jsx'), 'utf8');
  const runtime = fs.readFileSync(path.join(__dirname, '../src/ai/aiRuntime.js'), 'utf8');
  const appActions = fs.readFileSync(path.join(__dirname, '../src/app/appActions.js'), 'utf8');
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');

  assert.match(plugins, /id: 'zotero-reader'/);
  assert.match(settings, /draft\.type === 'zotero-reader'/);
  assert.match(app, /const zoteroReaderEnabled = plugins\.some/);
  assert.match(app, /id: 'zotero-search'/);
  assert.match(app, /id: 'zotero-read'/);
  assert.match(app, /readOnly: true/);
  assert.match(app, /window\.mn\.zotero\.search/);
  assert.match(app, /window\.mn\.zotero\.read/);
  assert.match(ai, /runZoteroDocumentRequest/);
  assert.match(ai, /const cleanedQueries = \[/);
  assert.match(ai, /Zotero responded: Local API is not enabled/);
  assert.match(ai, /summarizeZoteroRead/);
  assert.match(app, /aiHidden: true/);
  assert.match(appActions, /filter\(action => !action\.aiHidden\)/);
  assert.match(runtime, /zotero/);
  assert.match(runtime, /function isLikelyDocumentQuestion/);
  assert.match(runtime, /function makeZoteroSearchPlan/);
  assert.match(main, /const zotero = require\('\.\/lib\/zotero'\)/);
  assert.match(main, /ipcMain\.handle\('mn:zotero\.search'/);
  assert.match(preload, /zotero: \{/);
  assert.match(preload, /read: \(payload\) => ipcRenderer\.invoke\('mn:zotero\.read', payload\)/);
});

test('Release metadata targets renamed VispNote repository', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'));
  const lock = JSON.parse(fs.readFileSync(path.join(__dirname, '../package-lock.json'), 'utf8'));
  const workflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/release-builds.yml'), 'utf8');
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings/settings.jsx'), 'utf8');
  const aiSource = fs.readFileSync(path.join(__dirname, '../lib/ai.js'), 'utf8');
  const rendererEntry = fs.readFileSync(projectPaths.src.main, 'utf8');

  assert.match(pkg.version, /^\d+\.\d+\.\d+$/);
  assert.equal(lock.version, pkg.version);
  assert.equal(lock.packages[''].version, pkg.version);
  assert.deepEqual(pkg.files, [
    'vispnote.html',
    'main.js',
    'preload.js',
    'assets/',
    'build/renderer/',
    'lib/',
    'src/',
    'scripts/linux-after-install.sh',
    'scripts/before-pack.js',
    'scripts/build-renderer.js',
    'scripts/verify-packaged-renderer.js',
    'electron-builder.yml',
  ]);
  assert.equal(pkg.homepage, 'https://github.com/djkeshawa/visp-note#readme');
  assert.equal(pkg.repository.url, 'https://github.com/djkeshawa/visp-note.git');
  assert.equal(pkg.scripts['build:renderer'], 'node scripts/build-renderer.js');
  assert.equal(pkg.scripts['verify:package-renderer'], 'node scripts/verify-packaged-renderer.js');
  assert.equal(pkg.scripts.prebuild, 'npm run build:renderer');
  assert.equal(pkg.dependencies['@babel/standalone'], undefined);
  const rendererBuild = fs.readFileSync(path.join(__dirname, '../scripts/build-renderer.js'), 'utf8');
  assert.match(rendererBuild, /esbuild\.buildSync/);
  assert.match(rendererBuild, /bundle: true/);
  assert.match(rendererEntry, /React\.createElement\(window\.MnApp\)/);
  assert.match(fs.readFileSync(path.join(__dirname, '../electron-builder.yml'), 'utf8'), /beforePack: scripts\/before-pack\.js/);
  assert.match(fs.readFileSync(path.join(__dirname, '../scripts/before-pack.js'), 'utf8'), /Refusing to package/);
  assert.match(fs.readFileSync(path.join(__dirname, '../scripts/verify-packaged-renderer.js'), 'utf8'), /Wrong-platform better-sqlite3 native module/);
  assert.match(fs.readFileSync(path.join(__dirname, '../scripts/verify-packaged-renderer.js'), 'utf8'), /Wrong-platform sqlite-vec package/);
  assert.match(workflow, /name: VispNote-\$\{\{ matrix\.name \}\}/);
  assert.match(workflow, /Verify packaged renderer bundle/);
  assert.match(workflow, /--title "VispNote \$\{tag\}"/);
  assert.match(workflow, /Automated VispNote desktop release/);
  assert.match(settings, /Version \{version\} · Prototype/);
  assert.match(aiSource, /headers\['HTTP-Referer'\] = 'https:\/\/github\.com\/djkeshawa\/visp-note'/);
  assert.match(aiSource, /headers\['X-Title'\] = 'VispNote'/);
});

test('Release builds omit AppX and MSIX Store package targets', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'));
  const builder = fs.readFileSync(path.join(__dirname, '../electron-builder.yml'), 'utf8');
  const workflow = fs.readFileSync(path.join(__dirname, '../.github/workflows/release-builds.yml'), 'utf8');

  assert.equal(pkg.scripts['build:win:appx'], undefined);
  assert.equal(pkg.scripts['build:win:msix'], undefined);
  assert.equal(pkg.scripts['build:win:store'], undefined);
  assert.doesNotMatch(builder, /^appx:/m);
  assert.doesNotMatch(workflow, /windows-appx-x64/);
  assert.doesNotMatch(workflow, /windows-msix-x64/);
  assert.doesNotMatch(workflow, /dist\/\*\.appx/);
  assert.doesNotMatch(workflow, /dist\/\*\.msix/);
  assert.equal(fs.existsSync(path.join(__dirname, '../electron-builder-msix.yml')), false);
  assert.equal(fs.existsSync(path.join(__dirname, '../docs/microsoft-store-submission.md')), false);
});

test('Vault switcher uses VispNote icon instead of letter tiles', () => {
  const sidebar = fs.readFileSync(path.join(__dirname, '../src/panels/sidebar.jsx'), 'utf8');

  assert.match(sidebar, /const VAULT_ICON_SRC = 'assets\/vispnote-icon\.png'/);
  assert.match(sidebar, /function MnVaultIcon/);
  assert.match(sidebar, /<img src=\{VAULT_ICON_SRC\} alt="" aria-hidden="true"/);
  assert.match(sidebar, /<MnVaultIcon T=\{T\} size=\{22\} active \/>/);
  assert.match(sidebar, /<MnVaultIcon T=\{T\} size=\{20\} active=\{active\} \/>/);
  assert.match(sidebar, /Switch vault/);
  assert.match(sidebar, /vaultKindLabel/);
  assert.match(sidebar, /vaultNoteLabel/);
  assert.match(sidebar, /maxHeight: 260/);
  assert.match(sidebar, /aria-haspopup="menu"/);
  assert.match(sidebar, /onRefreshVaults\(\{ reloadActive: false, reason: 'vault-dropdown' \}\)/);
  assert.match(sidebar, /Rename vault/);
  assert.doesNotMatch(sidebar, /activeVault\?\.name \|\| 'm'\)\[0\]\.toLowerCase/);
  assert.doesNotMatch(sidebar, /v\.name\[0\]\.toLowerCase/);
});

test('Fallback spell checker underlines misspellings and offers replacements', () => {
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');

  assert.match(main, /function spellcheckWords/);
  assert.match(main, /SPELL_DICTIONARY_PATHS/);
  assert.match(main, /const SPELL_SUGGESTION_CACHE_LIMIT = 1000/);
  assert.match(main, /async function loadSpellWords\(\)/);
  assert.match(main, /await fs\.promises\.readFile\(file, 'utf8'\)/);
  assert.match(main, /loadSpellWords\(\)\.catch/);
  assert.match(main, /spellSuggestionCache\.size >= SPELL_SUGGESTION_CACHE_LIMIT/);
  assert.match(main, /loadedDictionaryWords < MIN_USABLE_DICTIONARY_WORDS/);
  assert.match(main, /if \(!spellDictionaryAvailable\) return \{\}/);
  assert.match(main, /spellSuggestions\(word, dictionary\)/);
  assert.match(preload, /spellcheck: \(words\) => ipcRenderer\.invoke\('mn:spellcheck', words\)/);
  assert.match(outliner, /function mnRenderSpellCheckedText/);
  assert.match(outliner, /textDecorationStyle: 'wavy'/);
  assert.match(outliner, /MnSpellSuggestionMenu/);
  assert.match(outliner, /window\.mn\.spellcheck\(words\)/);
  assert.match(outliner, /applySpellSuggestion/);
});

test('Workflow notes can be archived from workflow boards only', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const appRuntime = fs.readFileSync(path.join(__dirname, '../src/app/appRuntime.js'), 'utf8');
  const appShell = fs.readFileSync(path.join(__dirname, '../src/app/appShell.jsx'), 'utf8');
  const panels = fs.readFileSync(path.join(__dirname, '../src/panels/panels.jsx'), 'utf8');
  const store = fs.readFileSync(path.join(__dirname, '../lib/store.js'), 'utf8');
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');
  const blockFeatures = fs.readFileSync(path.join(__dirname, '../src/editor/blockFeatures.jsx'), 'utf8');
  const editor = fs.readFileSync(path.join(__dirname, '../src/editor/editor.jsx'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');
  const outline = fs.readFileSync(path.join(__dirname, '../src/editor/outline.jsx'), 'utf8');
  const notelist = fs.readFileSync(path.join(__dirname, '../src/panels/notelist.jsx'), 'utf8');
  const aiSource = fs.readFileSync(path.join(__dirname, '../lib/ai.js'), 'utf8');
  const ai = fs.readFileSync(path.join(__dirname, '../src/ai/ai.jsx'), 'utf8');
  const ollama = fs.readFileSync(path.join(__dirname, '../lib/ollama.js'), 'utf8');
  const helpers = fs.readFileSync(path.join(__dirname, '../src/app/appHelpers.js'), 'utf8');

  assert.match(helpers, /workflowArchived: !!note\.workflowArchived/);
  assert.match(helpers, /if \(note\.workflowArchived\) \{/);
  assert.match(helpers, /archivedNotes\.push/);
  assert.match(app, /const updateWorkflowArchived = useCallbackA/);
  assert.match(app, /archivedNotes=\{workflowViewData\.archivedNotes\}/);
  assert.match(app, /onSetWorkflowArchived=\{updateWorkflowArchived\}/);
  assert.match(appRuntime, /"workflowStates": null/);
  assert.match(app, /mnNormalizeWorkflowStatesForApp/);
  assert.match(app, /const normalWorkflowStates = useMemoA/);
  assert.match(app, /const novelistWorkflowStates = useMemoA/);
  assert.match(app, /activeVault\?\.novelistMode \? novelistWorkflowStates : normalWorkflowStates/);
  assert.match(app, /setWorkflowStates\?\.\(workflowStates\)/);
  assert.match(app, /const updateWorkflowStates = useCallbackA/);
  assert.match(app, /saveVaultMeta\(activeVaultId, \{ workflowStates: next \}\)/);
  assert.match(app, /onWorkflowStatesChange=\{updateWorkflowStates\}/);
  assert.doesNotMatch(app, /countFor\('WAIT'\) \+ countFor\('LATER'\)/);
  assert.doesNotMatch(app, /countFor\('DONE'\) \+ countFor\('CANCELLED'\)/);

  assert.match(panels, /archivedNotes = \[\]/);
  assert.match(panels, /ArchiveButton/);
  assert.match(panels, /Archive note from workflow/);
  assert.match(panels, /Archived from workflow/);
  assert.match(panels, /\{showArchived \? <ArchivedNotes \/> : \(/);
  assert.match(panels, /Restore/);
  assert.match(panels, /archiveNote\(note\.id, false\)/);
  assert.match(panels, /renderWorkflowStateManager/);
  assert.match(panels, /Array\.isArray\(states\) && states\.length === 0 \? \[\]/);
  assert.doesNotMatch(panels, /disabled=\{\(workflowStates \|\| \[\]\)\.length <= 1\}/);
  assert.match(appRuntime, /if \(Array\.isArray\(states\) && states\.length === 0\) return \[\]/);
  assert.match(blockFeatures, /if \(Array\.isArray\(states\) && states\.length === 0\) return \[\]/);
  assert.match(panels, /new column/);
  assert.match(panels, /addWorkflowState/);
  assert.match(panels, /removeWorkflowState/);
  assert.match(panels, /onWorkflowStatesChange && onWorkflowStatesChange/);
  assert.match(panels, /const \[dragOverState, setDragOverState\] = useStateP\(null\)/);
  assert.match(panels, /const \[dragPreview, setDragPreview\] = useStateP\(null\)/);
  assert.match(panels, /const dragItemRef = useRefP\(null\)/);
  assert.match(panels, /setActiveDragItem/);
  assert.match(panels, /clearActiveDragItem/);
  assert.match(panels, /updateDragPreview/);
  assert.match(panels, /setTransparentDragImage/);
  assert.match(panels, /const WorkflowDragPreview = \(\) =>/);
  assert.match(panels, /suppressCardClickRef/);
  assert.match(panels, /workflowStateFromPoint/);
  assert.match(panels, /beginCardPointerDrag/);
  assert.match(panels, /data-mn-workflow-state=\{state\.id\}/);
  assert.match(panels, /window\.addEventListener\('pointermove', onMove\)/);
  assert.match(panels, /onDragStart=\{\(e\) =>/);
  assert.match(panels, /e\.dataTransfer\.setData\('text\/mn-workflow', payload\)/);
  assert.match(panels, /onDrag=\{\(e\) =>/);
  assert.match(panels, /Release to move to \{state\.id\}/);
  assert.match(panels, /types\.includes\('text\/mn-note'\)/);
  assert.match(panels, /types\.includes\('text\/plain'\)/);
  assert.match(panels, /readDropNoteId/);
  assert.match(panels, /moveWorkflowNote\(noteId, null, state\.id\)/);
  assert.match(panels, /marginRight: 54/);
  assert.match(notelist, /draggable/);
  assert.match(notelist, /e\.dataTransfer\.setData\('text\/mn-note', payload\)/);
  assert.match(panels, /SummaryStat label="Columns"/);
  assert.match(panels, /SummaryStat label="Active cols"/);
  assert.doesNotMatch(panels, /const waitingCount = countFor\('WAIT'\) \+ countFor\('LATER'\)/);
  assert.doesNotMatch(panels, /const closedCount = countFor\('DONE'\) \+ countFor\('CANCELLED'\)/);

  assert.match(store, /workflowArchived: !!fm\.workflowArchived/);
  assert.match(store, /workflowArchived: !!note\.workflowArchived/);
  assert.match(blockFeatures, /mnNormalizeWorkflowStates/);
  assert.match(blockFeatures, /mnNormalizeWorkflowId/);
  assert.match(blockFeatures, /let MN_WORKFLOW_STATES = MN_DEFAULT_WORKFLOW_STATES/);
  assert.match(blockFeatures, /Object\.prototype\.hasOwnProperty\.call\(state \|\| \{\}, 'next'\)/);
  assert.match(blockFeatures, /Object\.prototype\.hasOwnProperty\.call\(fallback, 'next'\)/);
  assert.match(blockFeatures, /next: state\.next === undefined/);
  assert.match(blockFeatures, /safe\[index \+ 1\]\?\.id \|\| null/);
  assert.match(blockFeatures, /function mnWorkflowIsClosed\(state\)/);
  assert.match(blockFeatures, /mnWorkflowIsClosed,/);
  assert.match(blockFeatures, /setWorkflowStates: mnSetWorkflowStates/);
  assert.match(blockFeatures, /DEFAULT_WORKFLOW_STATES/);
  assert.match(panels, /const isClosedState = \(state\) => window\.MN_LOGSEQ\?\.mnWorkflowIsClosed/);
  assert.doesNotMatch(panels, /textDecoration: isClosedState\(state\) \? 'line-through' : 'none'/);
  assert.doesNotMatch(panels, /textDecoration:[\s\S]{0,80}line-through[\s\S]{0,80}No preview/);
  assert.doesNotMatch(panels, /state\.id === 'DONE' \|\| state\.id === 'CANCELLED'/);
  assert.match(outliner, /function mnWorkflowSlashCommands/);
  assert.match(outliner, /MN_NOVELIST_SLASH_CMDS/);
  assert.match(outliner, /options\.novelistMode \? MN_NOVELIST_SLASH_CMDS : \[\]/);
  assert.match(outliner, /plot-points/);
  assert.match(outliner, /One plot point per line/);
  assert.match(outliner, /updateBeatsText/);
  assert.doesNotMatch(outliner, /Add beat/);
  assert.doesNotMatch(outliner, /Remove beat/);
  assert.match(outliner, /Find page to link/);
  assert.match(outliner, /No available pages/);
  assert.match(outliner, /contexts: \[\.\.\.contexts, `\[\[\$\{title\}\]\]`\]/);
  assert.match(outliner, /aiActive=\{aiActive\}/);
  assert.match(outliner, /AI working/);
  assert.match(outliner, /mn-ai-live-dots/);
  assert.match(outliner, /function MnInlineAiPreview/);
  assert.match(outliner, /AI preview/);
  assert.match(outliner, /window\.MN_AI_REPORT\?\.report/);
  assert.match(outliner, /Report AI output/);
  assert.match(outliner, /mn-inline-ai-preview-streaming/);
  assert.match(editor, /noteId=\{note\.id\}/);
  assert.match(outliner, /noteIdRef/);
  assert.match(outliner, /previewForCurrentNote/);
  assert.match(outliner, /makeAiPreview\(requestNoteId/);
  assert.match(outliner, /const pageContinuationInstruction/);
  assert.match(outliner, /Continue from the end of it/);
  assert.match(outliner, /const appendPageWrite = actionId === 'write' && pageBlocks\.length > 0/);
  assert.match(outliner, /const appendPageBlocks/);
  assert.match(outliner, /kind: 'append-page'/);
  assert.match(outliner, /appendPageBlocks\(preview\.text\)/);
  assert.match(outliner, /plotPointsAction: 'write-scene'/);
  assert.match(outliner, /const appendPlotWrite = payload\.plotPointsAction === 'write-scene'/);
  assert.match(outliner, /Existing page context/);
  assert.match(outliner, /appended to the bottom of the page/);
  assert.match(outliner, /function[^\n]*plotPointsInstruction|const plotPointsInstruction/);
  assert.match(outliner, /Linked context pages/);
  assert.match(outliner, /kind: 'insert-after'/);
  assert.match(outliner, /insertBlocksAfter\(preview\.target\.blockId, parseAiBlocks\(preview\.text\)\)/);
  assert.match(outliner, /window\.mn\.ai\.editStream/);
  assert.match(preload, /editStream:\(payload = \{\}, onChunk\)/);
  assert.match(main, /mn:ai\.editStream/);
  assert.match(aiSource, /async function editTextStream/);
  assert.match(ollama, /async function chatStream/);
  assert.match(ai, /window\.mn\?\.ai\?\.askStream/);
  assert.match(ai, /window\.mn\?\.ai\?\.chatStream/);
  assert.match(ai, /function mnAskMessageId/);
  assert.match(ai, /key=\{m\.id\}/);
  assert.match(ai, /onToken: appendAssistantToken/);
  assert.match(preload, /askStream: \(vaultId, query, options = \{\}, onChunk\)/);
  assert.match(preload, /chatStream:\(payload = \{\}, onChunk\)/);
  assert.match(preload, /delete cleanOptions\.onToken/);
  assert.match(preload, /delete cleanPayload\.onToken/);
  assert.match(main, /mn:ai\.askStream/);
  assert.match(main, /mn:ai\.chatStream/);
  assert.match(main, /function sendIpcChunk/);
  assert.match(main, /evt\.sender\?\.isDestroyed\?\.\(\)/);
  assert.match(aiSource, /async function askStream/);
  assert.match(aiSource, /async function chatStream/);
  assert.match(ollama, /const CHAT_TIMEOUT_MS = 180000/);
  assert.match(outline, /window\.MN_LOGSEQ\?\.WORKFLOW_STATES/);
  assert.doesNotMatch(outline, /\^\(TODO\|DOING\|DONE\|LATER\|NOW\|WAIT\|CANCELLED\)/);
  assert.match(notelist, /const workflowPattern = states/);
  assert.doesNotMatch(notelist, /\^\(TODO\|DOING\|DONE\|LATER\|NOW\|WAIT\|CANCELLED\)/);
  assert.match(appShell, /function MnReminderCenter\(\{ open, items, dueCount, onToggle, onClose, onOpenNote, topOffset = 14, T \}\)/);
  assert.match(appShell, /top: topOffset/);
  assert.match(app, /const reminderCenterTop = view === 'ai' \? 17 : 14/);
  assert.match(app, /topOffset=\{reminderCenterTop\}/);
});

test('Stabilization wiring avoids stale UI and native dialogs', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app/app.jsx'), 'utf8');
  const appRuntime = fs.readFileSync(path.join(__dirname, '../src/app/appRuntime.js'), 'utf8');
  const appShell = fs.readFileSync(path.join(__dirname, '../src/app/appShell.jsx'), 'utf8');
  const appNovelistSource = fs.readFileSync(path.join(__dirname, '../src/app/appNovelist.js'), 'utf8');
  const panelHelpersSource = fs.readFileSync(path.join(__dirname, '../src/panels/panelHelpers.js'), 'utf8');
  const html = fs.readFileSync(path.join(__dirname, '../vispnote.html'), 'utf8');
  const rendererEntry = fs.readFileSync(projectPaths.src.main, 'utf8');
  const notelist = fs.readFileSync(path.join(__dirname, '../src/panels/notelist.jsx'), 'utf8');
  const editor = fs.readFileSync(path.join(__dirname, '../src/editor/editor.jsx'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/editor/outliner.jsx'), 'utf8');
  const blockFeatures = fs.readFileSync(path.join(__dirname, '../src/editor/blockFeatures.jsx'), 'utf8');
  const panels = fs.readFileSync(path.join(__dirname, '../src/panels/panels.jsx'), 'utf8');
  const store = fs.readFileSync(path.join(__dirname, '../lib/store.js'), 'utf8');
  const main = fs.readFileSync(path.join(__dirname, '../main.js'), 'utf8');
  const preload = fs.readFileSync(path.join(__dirname, '../preload.js'), 'utf8');

  assert.match(appShell, /function MnAppNoticeDialog/);
  assert.match(html, /src="build\/renderer\/app\.js"/);
  const entryIndex = source => rendererEntry.indexOf(`import './${source}';`);
  assert.ok(entryIndex('app/appHelpers.js') < entryIndex('app/app.jsx'));
  assert.ok(entryIndex('app/appHelpers.js') < entryIndex('app/appMutations.js'));
  assert.ok(entryIndex('app/appMutations.js') < entryIndex('app/app.jsx'));
  assert.ok(entryIndex('app/appMutations.js') < entryIndex('app/appCanvasActions.js'));
  assert.ok(entryIndex('app/appCanvasActions.js') < entryIndex('app/app.jsx'));
  assert.match(appRuntime, /const MN_APP_HELPERS = window\.MN_APP_HELPERS/);
  assert.match(appRuntime, /const MN_APP_MUTATIONS = window\.MN_APP_MUTATIONS/);
  assert.match(appRuntime, /const MN_APP_CANVAS_ACTIONS = window\.MN_APP_CANVAS_ACTIONS/);
  assert.match(app, /const searchSeq = useRefA\(0\)/);
  assert.match(app, /if \(seq === searchSeq\.current && res\.ok\) setSearchHits/);
  assert.match(app, /Load first, then switch atomically/);
  assert.match(panelHelpersSource, /root\.mnWriteNovelistAiConfig = api\.mnWriteNovelistAiConfig/);
  assert.match(app, /const duplicateNote = useCallbackA/);
  assert.match(app, /showAppNotice\('Could not create vault'/);
  assert.doesNotMatch(app, /alert\(/);
  assert.doesNotMatch(app, /window\.prompt/);

  assert.match(notelist, /onRenameNote/);
  assert.match(notelist, /onDuplicateNote/);
  assert.match(notelist, /onDeleteNote/);
  assert.match(notelist, /onContextMenu=\{\(e\) =>/);
  assert.match(editor, /onDuplicate/);
  assert.match(editor, /title="Duplicate note"/);

  assert.match(outliner, /const \[aiPrompt, setAiPrompt\]/);
  assert.match(outliner, /role="dialog"/);
  assert.match(outliner, /Marker: \$\{state\.id\}/);
  assert.doesNotMatch(outliner, /window\.prompt/);
  assert.match(blockFeatures, /Block marker/);

  assert.match(store, /novelistAiConfig/);
  assert.match(main, /flushRendererDirtyNotes/);
  assert.match(preload, /onFlushDirtyNotes/);
  assert.match(app, /onNew=\{\(\) => createNote\(\)\}/);
  assert.match(app, /const themeMap = window\.MN_THEMES \|\| \{\}/);
  assert.match(panels, /initialAiConfig = null/);
  assert.match(panels, /onAiConfigChange && onAiConfigChange\(next\)/);
  assert.match(appNovelistSource, /function mnReplaceWikiLinkTitle/);
  assert.match(app, /window\.mnWriteNovelistAiConfig\?\.\(activeVault\.novelistAiConfig, activeVaultId\)/);
});
