const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const ops = require('../src/editorOps.js');
const tableOps = require('../src/tableOps.js');
const appHelpers = require('../src/appHelpers.js');
const appNovelist = require('../src/appNovelist.js');
const appMutations = require('../src/appMutations.js');
const appCanvasActions = require('../src/appCanvasActions.js');
const panelHelpers = require('../src/panelHelpers.js');
const { block, loadOutlineForTest, withIsolatedStore } = require('./helpers/common.js');

test('Canvas editor supports expected drawing, color, clipboard, and delete interactions', () => {
  const canvas = fs.readFileSync(path.join(__dirname, '../src/canvas.jsx'), 'utf8');

  assert.match(canvas, /id: 'pen'/);
  assert.match(canvas, /id: 'arrow'/);
  assert.match(canvas, /id: 'diamond'/);
  assert.match(canvas, /id: 'triangle'/);
  assert.match(canvas, /id: 'eraser'/);
  assert.match(canvas, /function MnCanvasToolIcon/);
  assert.match(canvas, /aria-label=\{tool\.label\}/);
  assert.match(canvas, /mnCanvasIconToolButton/);
  assert.match(canvas, /function MnCanvasContextMenu/);
  assert.match(canvas, /onContextMenu=\{\(e\) => e\.preventDefault\(\)\}/);
  assert.match(canvas, /Delete object/);
  assert.match(canvas, /copyElements/);
  assert.match(canvas, /pasteElements/);
  assert.match(canvas, /navigator\.clipboard/);
  assert.match(canvas, /key === 'c'/);
  assert.match(canvas, /key === 'x'/);
  assert.match(canvas, /key === 'v'/);
  assert.match(canvas, /x2: point\.x/);
  assert.match(canvas, /y2: point\.y/);
  assert.match(canvas, /points: \[/);
  assert.match(canvas, /mnCanvasArrowHead/);
  assert.match(canvas, /element\.type === 'diamond'/);
  assert.match(canvas, /element\.type === 'triangle'/);
  assert.match(canvas, /tool === 'eraser'/);
  assert.match(canvas, /function MnCanvasColorControl/);
  assert.match(canvas, /type="color"/);
  assert.match(canvas, /applyColor\('stroke'/);
  assert.match(canvas, /applyColor\('fill'/);
  assert.match(canvas, /function MnCanvasDeleteDialog/);
  assert.match(canvas, /role="dialog"/);
  assert.doesNotMatch(canvas, /window\.confirm\('Delete this canvas\?'\)/);
  assert.match(canvas, /setPointerCapture/);
  assert.match(canvas, /releasePointerCapture/);
  assert.match(canvas, /rootRef\.current\?\.focus\(\)/);
  assert.match(canvas, /saveTitle\(\); onBack && onBack\(\)/);
  assert.doesNotMatch(canvas, /if \(action\.mode === 'create'\) setTool\('select'\)/);
  assert.match(canvas, /const \[selectedIds, setSelectedIds\]/);
  assert.match(canvas, /function mnCanvasSelectionBounds/);
  assert.match(canvas, /function mnCanvasMoveElement/);
  assert.match(canvas, /const undoCanvas = \(\) =>/);
  assert.match(canvas, /const redoCanvas = \(\) =>/);
  assert.match(canvas, /isMod && key === 'z'/);
  assert.match(canvas, /isMod && key === 'y'/);
  assert.match(canvas, /const \[marquee, setMarquee\]/);
  assert.match(canvas, /mode: 'marquee'/);
  assert.match(canvas, /function MnCanvasResizeHandles/);
  assert.match(canvas, /mode: 'resize'/);
  assert.match(canvas, /alignSelected\('left'\)/);
  assert.match(canvas, /distributeSelected\('x'\)/);
  assert.match(canvas, /const fitToScreen = \(\) =>/);
  assert.match(canvas, /const \[spaceDown, setSpaceDown\]/);
  assert.match(canvas, /mode: 'pan'/);
  assert.match(canvas, /const \[editingTextId, setEditingTextId\]/);
  assert.match(canvas, /<textarea/);
  assert.match(canvas, /svg\.createSVGPoint\(\)/);
  assert.match(canvas, /screenMatrix\.inverse\(\)/);
  assert.match(canvas, /const showSelectionUi = tool === 'select'/);
  assert.match(canvas, /selected=\{showSelectionUi && selectedIds\.includes\(el\.id\)\}/);
  assert.match(canvas, /e\.button === 0 && tool !== 'select'/);
  assert.match(canvas, /beginCreate\(e, toCanvasPoint\(e\)\)/);

  const canvasActions = fs.readFileSync(path.join(__dirname, '../src/appCanvasActions.js'), 'utf8');
  assert.match(canvasActions, /setActiveCanvas\(current => current\?\.id === saved\.id \? saved : current\)/);
});

test('Note delete confirmation uses themed in-app dialog', () => {
  const app = fs.readFileSync(path.join(__dirname, '../src/app.jsx'), 'utf8');
  const appShell = fs.readFileSync(path.join(__dirname, '../src/appShell.jsx'), 'utf8');

  assert.match(appShell, /function MnDeleteNoteDialog/);
  assert.match(appShell, /className="mn-delete-note-dialog"/);
  assert.match(appShell, /role="dialog"/);
  assert.match(appShell, /aria-modal="true"/);
  assert.match(app, /setDeleteTargetId\(id\)/);
  assert.match(app, /onDelete=\{\(\) => requestDeleteNote\(selectedNote\.id\)\}/);
  assert.match(app, /onConfirm=\{\(\) => deleteNote\(deleteTargetNote\.id\)\}/);
  assert.match(appShell, /background: T\.danger/);
  assert.doesNotMatch(app, /confirm\(/);
});

test('Launch screen uses VispNote logo with pastel blooming light design', () => {
  const html = fs.readFileSync(path.join(__dirname, '../vispnote.html'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '../src/app.jsx'), 'utf8');
  const appShell = fs.readFileSync(path.join(__dirname, '../src/appShell.jsx'), 'utf8');
  const loadingLogo = fs.statSync(path.join(__dirname, '../assets/vispnote-loading-transparent.png'));
  const appIcon = fs.statSync(path.join(__dirname, '../assets/vispnote-icon.png'));

  assert.match(html, /<title>VispNote<\/title>/);
  assert.match(html, /<link rel="icon" type="image\/png" href="assets\/vispnote-icon\.png" \/>/);
  assert.match(html, /@keyframes mnLightBloom/);
  assert.match(html, /@keyframes mnLightWash/);
  assert.match(html, /@keyframes mnBootProgress/);
  assert.match(html, /@keyframes mnStatusBreath/);
  assert.match(html, /mn-boot-light-field/);
  assert.match(html, /mn-light-bloom/);
  assert.match(html, /radial-gradient\(circle at center/);
  assert.match(html, /linear-gradient\(90deg, #f3bfd8 0%, #a9c2ff 48%, #9fe2c9 100%\)/);
  assert.doesNotMatch(html, /filter: blur/);
  assert.doesNotMatch(html, /mn-light-ripple/);
  assert.doesNotMatch(html, /@keyframes mnPastelRipple/);
  assert.doesNotMatch(html, /@property --mn-ripple-radius/);
  assert.doesNotMatch(html, /--mn-ripple-radius/);
  assert.doesNotMatch(html, /width: max\(180vw, 180vh\)/);
  assert.doesNotMatch(html, /conic-gradient\(from 70deg/);
  assert.doesNotMatch(html, /@keyframes mnProgressGlow/);
  assert.doesNotMatch(html, /mn-pastel-float/);
  assert.doesNotMatch(html, /mn-boot-neural-field/);
  assert.doesNotMatch(html, /animateMotion/);
  assert.match(html, /mn-boot-brand/);
  assert.match(html, /mn-boot-logo/);
  assert.match(html, /aria-label="VispNote"/);
  assert.match(html, /src="assets\/vispnote-loading-transparent\.png"/);
  assert.match(html, /alt="VispNote"/);
  assert.match(html, /width: clamp\(340px, 54vw, 720px\)/);
  assert.match(html, /object-fit: contain/);
  assert.match(html, /mix-blend-mode: multiply/);
  assert.match(html, /mn-boot-title mn-boot-wordmark">VispNote/);
  assert.ok(loadingLogo.size > 0);
  assert.match(html, /Capture<\/span><i><\/i><span>Organize<\/span><i><\/i><span>Remember/);
  assert.match(html, /class="mn-boot-status">Opening vault and indexing notes/);
  assert.match(html, /class="mn-boot-progress"><div><\/div><\/div>/);
  assert.match(html, /prefers-reduced-motion: reduce/);
  assert.doesNotMatch(html, /@keyframes mnBootLogoTrace/);
  assert.doesNotMatch(html, /@keyframes mnBootLogoGlow/);
  assert.doesNotMatch(html, /@keyframes mnBootWordGlow/);
  assert.doesNotMatch(html, /mnBootLogoFloat/);
  assert.doesNotMatch(html, /mnBootWordGlow/);
  assert.match(html, /Connecting your workspace/);
  assert.match(appShell, /function MnBootLogo/);
  assert.match(appShell, /aria-label="VispNote"/);
  assert.match(appShell, /src="assets\/vispnote-loading-transparent\.png"/);
  assert.match(appShell, /alt="VispNote"/);
  assert.match(appShell, /className="mn-boot-title mn-boot-wordmark">VispNote/);
  assert.match(appShell, /<MnBootLogo \/>/);
  assert.match(appShell, /MN_LAUNCH_BLOOMS/);
  assert.doesNotMatch(appShell, /MN_LAUNCH_RIPPLES/);
  assert.match(appShell, /className="mn-boot-light-field"/);
  assert.match(appShell, /className="mn-light-bloom"/);
  assert.doesNotMatch(appShell, /className="mn-light-ripple"/);
  assert.match(appShell, /className="mn-boot-status"/);
  assert.match(appShell, /className="mn-boot-progress"/);
  assert.doesNotMatch(appShell, /MN_LAUNCH_FLOATS/);
  assert.doesNotMatch(appShell, /MN_LAUNCH_NEURAL_PATHS/);
  assert.ok(appIcon.size > 0);
});

test('App and editor font size settings use stepper controls', () => {
  const settings = fs.readFileSync(path.join(__dirname, '../src/settings.jsx'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '../src/app.jsx'), 'utf8');
  const outliner = fs.readFileSync(path.join(__dirname, '../src/outliner.jsx'), 'utf8');

  assert.match(settings, /function FontSizeStepper/);
  assert.match(settings, /label="App font size"/);
  assert.match(settings, /label="Font size"/);
  assert.match(app, /"appFontSize": "default"/);
  assert.match(app, /--mn-app-font-size/);
  assert.match(app, /width: '100vw'/);
  assert.match(app, /height: '100vh'/);
  assert.doesNotMatch(app, /transform: `scale\(\$\{appScale\}\)`/);
  assert.doesNotMatch(app, /width: `calc\(100vw \/ \$\{appScale\}\)`/);
  assert.match(outliner, /mnEditorFontScale/);
});
