const { createCaptureHelpers } = require('./helpers/captureHelpers.js');
const { createWorkflowHelpers } = require('./helpers/workflowHelpers.js');
const { createSmartViewHelpers } = require('./helpers/smartViewHelpers.js');
const { createRollupHelpers } = require('./helpers/rollupHelpers.js');
const { createContextualAiHelpers } = require('./helpers/contextualAiHelpers.js');
const { createNovelistHelpers } = require('../features/writer/novelistHelpers.js');
const { createNovelImportHelpers } = require('./helpers/novelImportHelpers.js');

const scope = {};
Object.assign(scope, createCaptureHelpers(scope));
Object.assign(scope, createWorkflowHelpers(scope));
Object.assign(scope, createSmartViewHelpers(scope));
Object.assign(scope, createRollupHelpers(scope));
Object.assign(scope, createContextualAiHelpers(scope));
Object.assign(scope, createNovelistHelpers(scope));
Object.assign(scope, createNovelImportHelpers(scope));

const PUBLIC_HELPERS = [
  "NOTE_TEMPLATES",
  "CAPTURE_DESTINATIONS",
  "CAPTURE_TEMPLATES",
  "SMART_VIEW_FORMAT",
  "PHASE5_METRICS_FORMAT",
  "PHASE5_METRIC_KEYS",
  "todayIsoDate",
  "expandTemplate",
  "templateById",
  "captureTemplateById",
  "captureTemplateChoices",
  "expandCaptureTemplate",
  "captureDestinationChoices",
  "captureDestinationById",
  "captureBuildAppendMarkdown",
  "captureBuildSavePlan",
  "phase5MetricChoices",
  "phase5NormalizeMetricKey",
  "phase5SanitizeMetricDetails",
  "phase5SanitizeMetrics",
  "phase5RecordMetric",
  "phase5MetricCount",
  "zoteroCleanItemKey",
  "zoteroNormalizeSource",
  "zoteroBuildSourceNoteDraft",
  "zoteroFindSourceNote",
  "zoteroBuildSourceNotePlan",
  "filterCommands",
  "decorateNotesWithSearchDetails",
  "normalizeWorkflowStatus",
  "workflowNotePreview",
  "collectWorkflowNotes",
  "reminderKey",
  "taskItemKey",
  "collectTaskItems",
  "collectReminderItems",
  "rollupNormalizeRange",
  "rollupNormalizeGroupBy",
  "rollupDateKey",
  "rollupDateRangeBounds",
  "rollupDateKeyInRange",
  "rollupTitleDateKey",
  "rollupNoteDateKey",
  "rollupIsOlderGroup",
  "smartViewNormalizeDefinition",
  "smartViewMatchesNote",
  "smartViewQueryNotes",
  "smartViewQueryActions",
  "smartViewQuery",
  "smartViewValidateSavedDefinition",
  "smartViewSerializeDefinition",
  "smartViewParseDefinitionText",
  "smartViewParseEmbedBlock",
  "smartViewUpsertSavedDefinition",
  "rollupGroupNotes",
  "rollupNotePreview",
  "rollupFilterTaskItems",
  "rollupFilterReminderItems",
  "rollupFindDailyNote",
  "rollupTaskReasonLabel",
  "rollupReminderReasonLabel",
  "agendaActionStatus",
  "agendaActionReasonLabel",
  "agendaActionDetail",
  "agendaDecorateActionItems",
  "agendaFilterActionItems",
  "agendaParseDeferMarker",
  "agendaStripDeferMarkers",
  "agendaCleanActionText",
  "agendaBuildTaskContent",
  "agendaIsDeferred",
  "agendaNormalizeActionIdentity",
  "agendaBodyHasActionText",
  "agendaReplaceUniqueSourceText",
  "agendaParseScheduleInput",
  "rollupAppendQuickTask",
  "rollupAppendReflection",
  "rollupBuildEndDayRecap",
  "rollupAppendEndDayRecap",
  "contextualAiProviderMeta",
  "contextualAiSourceFromNote",
  "contextualAiSourcesFromNotes",
  "contextualAiNormalizeSection",
  "contextualAiNormalizeSections",
  "contextualAiResult",
  "contextualAiMarkdownMarkers",
  "contextualAiCompareMarkdownMarkers",
  "contextualAiBuildTodayRecapContext",
  "contextualAiBuildTodayRecapPrompt",
  "digestStaleTodoItems",
  "digestUnlinkedRecentNotes",
  "digestActionItemKey",
  "digestUniqueActionItems",
  "digestResurfacedNotes",
  "contextualAiBuildTodayRecapResult",
  "reminderDisplayDate",
  "reminderStatusLabel",
  "novelistNoteId",
  "ensureNovelistTags",
  "buildNovelistStarterNotes",
  "dirtyNoteKey",
  "isNovelistNote",
  "normalizeNovelistLegacyTags",
  "normalizeNovelistLegacyBody",
  "ensureScenePlotPoints",
  "novelTitleKey",
  "novelWikiTitles",
  "replaceWikiLinkTitle",
  "bodyPropertyLineRe",
  "bodyPropertyValue",
  "bodyPropertyTitle",
  "bodyPropertyInsertIndex",
  "setBodyProperty",
  "removeBodyProperty",
  "bodyPropertyParts",
  "normalizeBodyPropertySyntax",
  "stripDuplicateTitleHeading",
  "normalizeNoteBody",
  "noteOrderValue",
  "compareStoryNotes",
  "novelOutlineLinks",
  "novelPropertyTitle",
  "novelHasWikiLink",
  "novelEnsureWikiLink",
  "novelEnsureWikiLinkInSection",
  "novelUpsertPropertyLink",
  "buildNovelistStructure",
  "normalizeNotes",
  "noteForDisk",
  "normalizeTagName",
  "parseDefaultTags",
  "NOVEL_IMPORT_KIND_TAGS",
  "normalizeNovelImportKind",
  "novelImportTagForKind",
  "normalizeNovelImportCandidates",
  "buildNovelImportBody",
  "mergeNovelImportBody",
  "buildNovelImportPlan"
];
const api = Object.fromEntries(PUBLIC_HELPERS.map(name => [name, scope[name]]));
module.exports = api;
